version: '3'

services:

  users:
    build:
      context: ./services/users
      dockerfile: Dockerfile-dev
    volumes:  # Mount code to container, to update the container whenever a change to the source code is made in dev
      - './services/users:/usr/src/app'
    ports:
      - 5001:5000
    environment:
      - FLASK_APP=project/__init__.py
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig # Load config for dev env