version: '3'

services:

  users:
    build:
      context: ./services/users
      dockerfile: Dockerfile-dev
    volumes:  # Mount code to container, to update the container whenever a change to the source code is made in dev
      - './services/users:/usr/src/app'
    ports:
      - 5001:5000
    environment:
      - FLASK_APP=project/__init__.py
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig # Load config for dev env
      - DATABASE_URL=postgres://postgres:postgres@users-db:5432/users_dev 
      - DATABASE_TEST_URL=postgres://postgres:postgres@users-db:5432/users_test
    depends_on:
      - users_db
  
  users_db:
    build:
      context: ./services/users/project/db
      dockerfile: Dockerfile
    ports:
      - 5435:5432 # Postgres will be available on port 5435 on the host machine and on port 5432 for services running in other containers
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres 
    